'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblDados
    Public Property ID As Integer
    Public Property EAN As Nullable(Of Long)
    Public Property Qtde As Nullable(Of Decimal)
    Public Property Preco As Nullable(Of Decimal)
    Public Property Total As Nullable(Of Decimal)
    Public Property NomeFiscalAbordagem As String
    Public Property Observacao As String
    Public Property Dia As Nullable(Of Date)
    Public Property NomeFiscalConstatou As String
    Public Property Hora As String
    Public Property NumCamera As String
    Public Property DVR As String
    Public Property idFilial As Nullable(Of Short)
    Public Property idReativaPreventiva As Nullable(Of Byte)
    Public Property DiaCadastro As Nullable(Of Date)
    Public Property idFurtante As Nullable(Of Byte)
    Public Property IdadeFurtante As Nullable(Of Byte)
    Public Property idEtiqueta As Nullable(Of Byte)

End Class
