'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblVenda_Mes
    Public Property Posto_Filial As Byte
    Public Property Ano As Short
    Public Property Mes As Byte
    Public Property Posto_Cod As Short
    Public Property Qtde As Nullable(Of Decimal)
    Public Property vlrVenda As Nullable(Of Decimal)

End Class
