<%@ Page Title="" Language="VB" MasterPageFile="~/MemberPages/Patrimonio/Patrimonio_Preventica_Reativa.master" AutoEventWireup="false" CodeFile="grafico_Empresa.aspx.vb" Inherits="MemberPages_Patrimonio_grafico_Empresa" %>

<%@ Register Assembly="DevExpress.Web.v18.2, Version=18.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" Namespace="DevExpress.Web" TagPrefix="dx" %>


<%@ Register Assembly="DevExpress.XtraCharts.v18.2.Web, Version=18.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" Namespace="DevExpress.XtraCharts.Web" TagPrefix="dxchartsui" %>
<%@ Register assembly="DevExpress.XtraCharts.v18.2, Version=18.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" namespace="DevExpress.XtraCharts" tagprefix="cc1" %>

<%@ Register Src="~/Controles/wucListaLojasComCorporacao.ascx" TagPrefix="uc1" TagName="wucListaLojasComCorporacao" %>
<%@ Register Src="~/Controles/wucAnoMes.ascx" TagPrefix="uc1" TagName="wucAnoMes" %>
<%@ Register Src="~/Controles/wucAno.ascx" TagPrefix="uc1" TagName="wucAno" %>
<%@ Register Src="~/Controles/wuciListaMes.ascx" TagPrefix="uc1" TagName="wuciListaMes" %>



<asp:Content ID="Content2" ContentPlaceHolderID="PatrimonioContent" Runat="Server">

    <div id="divAno" class="BGC_myBorder" style="float:left; margin-left: 15px; margin-top: -3px ">
        <uc1:wucAno runat="server" ID="cboAno" />
    </div>

    <div id="divMes" style="float:left; margin-left: 15px; margin-top: -3px ">
        <uc1:wuciListaMes runat="server" ID="cboMes" />
    </div>

    <div class="divBotaoAtualizar" style="float:left ; margin-left: 15px; margin-top: -4px ">
        <dx:ASPxButton ID="btnAtualizarEmpresa" runat="server" Text="Atualizar" AutoPostBack="False" Theme="Metropolis">
            <ClientSideEvents Click="function(s, e) {cbpPanel_Empresa.PerformCallback();}" />
        </dx:ASPxButton>
    </div>

    

  

    <dx:ASPxCallbackPanel ID="cbPanel_Empresa" ClientInstanceName="cbpPanel_Empresa" runat="server" Width="100%" SettingsLoadingPanel-Text="Aguarde. Atualizando" Theme="Metropolis">
<SettingsLoadingPanel Text="Aguarde. Atualizando"></SettingsLoadingPanel>
        <PanelCollection>
            <dx:PanelContent>

    <div style="width:100%">

    <dxchartsui:WebChartControl ID="graph_ValorRecuperado_Empresa_Periodo" runat="server" BackColor="#FFFFC0" DataSourceID="dsValorRecuperado_Empresa_Periodo" Height="450px" Width="1500px" >
        <diagramserializable>
            <cc1:XYDiagram>
                <axisx visibleinpanesserializable="-1" interlaced="True" labelvisibilitymode="AutoGeneratedAndCustom" minorcount="1" title-font="Tahoma, 9.75pt" visibility="True">
                    <qualitativescaleoptions autogrid="False" gridspacing="0.5" /><tickmarks minorlength="1" minorvisible="False" /><label angle="90">
                    </label>
                    <range sidemarginsenabled="True" />
                </axisx>
                <axisy visible="False" visibleinpanesserializable="-1">
                    <range sidemarginsenabled="True" />
                </axisy>
                <defaultpane backcolor="255, 255, 192">
                </defaultpane>
            </cc1:XYDiagram>
        </diagramserializable>
        <fillstyle>
            <optionsserializable>
                <cc1:SolidFillOptions />
            </optionsserializable>
        </fillstyle>
        <legend alignmenthorizontal="Center" alignmentvertical="BottomOutside" maxverticalpercentage="7" Visibility="False"></legend>
        <seriesserializable>
            <cc1:Series ArgumentDataMember="descMes" LabelsVisibility="True" Name="Series 1" ValueDataMembersSerializable="vlrTotalRecuperado" ArgumentScaleType="Qualitative" LegendName="Default Legend">
                <viewserializable>
                    <cc1:LineSeriesView ColorEach="True" MarkerVisibility="True" EnableAntialiasing="True">
                        <linemarkeroptions BorderVisible="True">
                        </linemarkeroptions>
                    <linestyle thickness="1" /></cc1:LineSeriesView>
                </viewserializable>
                <labelserializable>
                    <cc1:PointSeriesLabel Font="Tahoma, 9pt" LineVisible="True" TextOrientation="BottomToTop" Angle="90" ResolveOverlappingMode="Default" TextPattern="{V:n0}">
                        <fillstyle>
                            <optionsserializable>
                                <cc1:SolidFillOptions />
                            </optionsserializable>
                        </fillstyle>
                        <pointoptionsserializable>
                            <cc1:PointOptions>
                                <valuenumericoptions format="Currency" precision="0" />
                            </cc1:PointOptions>
                        </pointoptionsserializable>
                    </cc1:PointSeriesLabel>
                </labelserializable>
                <legendpointoptionsserializable>
                    <cc1:PointOptions>
                        <valuenumericoptions format="Currency" precision="0" />
                    </cc1:PointOptions>
                </legendpointoptionsserializable>
            </cc1:Series>
        </seriesserializable>
        <seriestemplate>
            <viewserializable>
                <cc1:LineSeriesView MarkerVisibility="True">
                    <linemarkeroptions BorderVisible="True">
                    </linemarkeroptions>
                </cc1:LineSeriesView>
            </viewserializable>
            <labelserializable>
                <cc1:PointSeriesLabel LineVisible="True">
                    <fillstyle>
                        <optionsserializable>
                            <cc1:SolidFillOptions />
                        </optionsserializable>
                    </fillstyle>
                    <pointoptionsserializable>
                        <cc1:PointOptions>
                        </cc1:PointOptions>
                    </pointoptionsserializable>
                </cc1:PointSeriesLabel>
            </labelserializable>
            <legendpointoptionsserializable>
                <cc1:PointOptions>
                </cc1:PointOptions>
            </legendpointoptionsserializable>
        </seriestemplate>
        <titles>
            <cc1:ChartTitle Font="Tahoma, 14pt" Indent="1" Text="Valor Recuperado por Mês - Empresa " WordWrap="True" />
        </titles>
        <crosshairoptions>
            <commonlabelpositionserializable>
                <cc1:CrosshairMousePosition />
            </commonlabelpositionserializable>
        </crosshairoptions>
        <tooltipoptions>
            <tooltippositionserializable>
                <cc1:ToolTipMousePosition />
            </tooltippositionserializable>
        </tooltipoptions>
    </dxchartsui:WebChartControl>
    <asp:SqlDataSource ID="dsValorRecuperado_Empresa_Periodo" runat="server" ConnectionString="<%$ ConnectionStrings:gerProjetosConnectionString %>" SelectCommand="Patrimonio.usp_TotalValorRecuperadoPorFilial" SelectCommandType="StoredProcedure">
        <SelectParameters>
            <asp:SessionParameter Name="Ano" SessionField="sANO" Type="Int16" />
            <asp:SessionParameter DefaultValue="99" Name="idFilial" Type="int16" />
        </SelectParameters>
    </asp:SqlDataSource>

    </div>
                                                                                          
    <br />
                                                    
    <dxchartsui:WebChartControl ID="graph_Total_Furto_Degustacao_daEMPRESA" runat="server" BackColor="#FFFFC0" DataSourceID="dsTotal_Furto_Degustacao_daEMPRESA" Height="450px" Width="1000px">
        <diagramserializable>
            <cc1:XYDiagram>
                <axisx visibleinpanesserializable="-1">
                    <label angle="90">
                    </label>
                    <range sidemarginsenabled="True" />
                </axisx>
                <axisy visible="False" visibleinpanesserializable="-1">
                    <range sidemarginsenabled="True" />
                </axisy>
                <defaultpane backcolor="255, 255, 192">
                </defaultpane>
            </cc1:XYDiagram>
        </diagramserializable>
        <fillstyle>
            <optionsserializable>
                <cc1:SolidFillOptions />
            </optionsserializable>
        </fillstyle>
        <legend alignmenthorizontal="Center" alignmentvertical="BottomOutside" maxverticalpercentage="7" Visibility="False"></legend>
        <seriesserializable>
            <cc1:Series ArgumentDataMember="Descricao" LabelsVisibility="True" Name="Series 1" ValueDataMembersSerializable="vlrTotal">
                <viewserializable>
                    <cc1:SideBySideBarSeriesView ColorEach="True">
                    </cc1:SideBySideBarSeriesView>
                </viewserializable>
                <labelserializable>
                    <cc1:SideBySideBarSeriesLabel Font="Tahoma, 9pt" LineVisible="True" TextOrientation="BottomToTop" TextPattern="{V:n0}">
                        <fillstyle>
                            <optionsserializable>
                                <cc1:SolidFillOptions />
                            </optionsserializable>
                        </fillstyle>
                        <pointoptionsserializable>
                            <cc1:PointOptions>
                                <valuenumericoptions format="Currency" precision="0" />
                            </cc1:PointOptions>
                        </pointoptionsserializable>
                    </cc1:SideBySideBarSeriesLabel>
                </labelserializable>
                <legendpointoptionsserializable>
                    <cc1:PointOptions>
                        <valuenumericoptions format="Currency" precision="0" />
                    </cc1:PointOptions>
                </legendpointoptionsserializable>
            </cc1:Series>
        </seriesserializable>
        <seriestemplate>
            <viewserializable>
                <cc1:SideBySideBarSeriesView>
                </cc1:SideBySideBarSeriesView>
            </viewserializable>
            <labelserializable>
                <cc1:SideBySideBarSeriesLabel LineVisible="True">
                    <fillstyle>
                        <optionsserializable>
                            <cc1:SolidFillOptions />
                        </optionsserializable>
                    </fillstyle>
                    <pointoptionsserializable>
                        <cc1:PointOptions>
                        </cc1:PointOptions>
                    </pointoptionsserializable>
                </cc1:SideBySideBarSeriesLabel>
            </labelserializable>
            <legendpointoptionsserializable>
                <cc1:PointOptions>
                </cc1:PointOptions>
            </legendpointoptionsserializable>
        </seriestemplate>
        <titles>
            <cc1:ChartTitle Font="Tahoma, 14pt" Indent="1" Text="Furto e Degustação da EMPRESA - Mês" WordWrap="True" />
        </titles>
        <crosshairoptions>
            <commonlabelpositionserializable>
                <cc1:CrosshairMousePosition />
            </commonlabelpositionserializable>
        </crosshairoptions>
        <tooltipoptions>
            <tooltippositionserializable>
                <cc1:ToolTipMousePosition />
            </tooltippositionserializable>
        </tooltipoptions>
    </dxchartsui:WebChartControl>
    <asp:SqlDataSource ID="dsTotal_Furto_Degustacao_daEMPRESA" runat="server" ConnectionString="<%$ ConnectionStrings:gerPerdasConnectionString %>" SelectCommand="Analises.usp_Total_Furto_Degustacao_daEMPRESA" SelectCommandType="StoredProcedure">
        <SelectParameters>
            <asp:SessionParameter Name="Ano" SessionField="sANO" Type="Int16" />
            <asp:SessionParameter Name="Mes" SessionField="sMES" Type="Byte" />
        </SelectParameters>
    </asp:SqlDataSource>
    <b>
    <asp:Label ID="Label5" runat="server"></asp:Label>
    </b>

    <br />

    <dxchartsui:WebChartControl ID="graph_Total_Furto_Degustacao_daEMPRESA_13_Mes" runat="server" BackColor="#FFFFC0" DataSourceID="dsValorRecuperadoEmpresa_13_Mes" Height="450px" Width="1000px">
        <diagramserializable>
            <cc1:XYDiagram>
                <axisx visibleinpanesserializable="-1">
                    <label angle="90">
                    </label>
                    <range sidemarginsenabled="True" />
                </axisx>
                <axisy visible="False" visibleinpanesserializable="-1">
                    <range sidemarginsenabled="True" />
                </axisy>
                <defaultpane backcolor="255, 255, 192">
                </defaultpane>
            </cc1:XYDiagram>
        </diagramserializable>
        <fillstyle>
            <optionsserializable>
                <cc1:SolidFillOptions />
            </optionsserializable>
        </fillstyle>
        <legend alignmenthorizontal="Center" alignmentvertical="BottomOutside" maxverticalpercentage="7" Visibility="False"></legend>
        <seriesserializable>
            <cc1:Series ArgumentDataMember="descMes" LabelsVisibility="True" Name="Series 1" ValueDataMembersSerializable="vlrTotal" SeriesPointsSorting="Ascending">
                <viewserializable>
                    <cc1:LineSeriesView ColorEach="True" MarkerVisibility="True">
                        <linemarkeroptions BorderVisible="True">
                        </linemarkeroptions>
                    </cc1:LineSeriesView>
                </viewserializable>
                <labelserializable>
                    <cc1:PointSeriesLabel Font="Tahoma, 9pt" LineVisible="True" TextOrientation="BottomToTop" TextPattern="{V:n0}">
                        <fillstyle>
                            <optionsserializable>
                                <cc1:SolidFillOptions />
                            </optionsserializable>
                        </fillstyle>
                        <pointoptionsserializable>
                            <cc1:PointOptions>
                                <valuenumericoptions format="Currency" precision="0" />
                            </cc1:PointOptions>
                        </pointoptionsserializable>
                    </cc1:PointSeriesLabel>
                </labelserializable>
                <legendpointoptionsserializable>
                    <cc1:PointOptions>
                        <valuenumericoptions format="Currency" precision="0" />
                    </cc1:PointOptions>
                </legendpointoptionsserializable>
            </cc1:Series>
        </seriesserializable>
        <seriestemplate>
            <viewserializable>
                <cc1:LineSeriesView MarkerVisibility="True">
                    <linemarkeroptions BorderVisible="True">
                    </linemarkeroptions>
                </cc1:LineSeriesView>
            </viewserializable>
            <labelserializable>
                <cc1:PointSeriesLabel LineVisible="True">
                    <fillstyle>
                        <optionsserializable>
                            <cc1:SolidFillOptions />
                        </optionsserializable>
                    </fillstyle>
                    <pointoptionsserializable>
                        <cc1:PointOptions>
                        </cc1:PointOptions>
                    </pointoptionsserializable>
                </cc1:PointSeriesLabel>
            </labelserializable>
            <legendpointoptionsserializable>
                <cc1:PointOptions>
                </cc1:PointOptions>
            </legendpointoptionsserializable>
        </seriestemplate>
        <titles>
            <cc1:ChartTitle Font="Tahoma, 14pt" Indent="1" Text="Empresa - Furto e Degustação - Últimos 13 Meses" WordWrap="True" />
        </titles>
        <crosshairoptions>
            <commonlabelpositionserializable>
                <cc1:CrosshairMousePosition />
            </commonlabelpositionserializable>
        </crosshairoptions>
        <tooltipoptions>
            <tooltippositionserializable>
                <cc1:ToolTipMousePosition />
            </tooltippositionserializable>
        </tooltipoptions>
    </dxchartsui:WebChartControl>
    <asp:SqlDataSource ID="dsValorRecuperadoEmpresa_13_Mes" runat="server" ConnectionString="<%$ ConnectionStrings:gerPerdasConnectionString %>" SelectCommand="Analises.usp_Total_Furto_Degustacao_daEMPRESA_13_Mes" SelectCommandType="StoredProcedure"></asp:SqlDataSource>
                                   

            </dx:PanelContent>
        </PanelCollection>
    </dx:ASPxCallbackPanel>

   
</asp:Content>

